import html2pdf from 'html2pdf.js'

export async function generateSimplePDF(element: HTMLElement, filename: string = 'document.pdf'): Promise<void> {
  const opt = {
    margin: 10,
    filename,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  }

  await html2pdf().from(element).set(opt).save()
}

export async function generateSimplePDFBlob(element: HTMLElement): Promise<Blob> {
  const opt = {
    margin: 10,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
  }

  return await html2pdf().from(element).set(opt).outputPdf('blob')
}

// 添加缺失的函数
export async function generateResumePDFBlobFromData(resumeContent: any, metadata: any): Promise<Blob> {
  // 创建临时DOM元素来生成PDF
  const tempDiv = document.createElement('div')
  tempDiv.innerHTML = `
    <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto;">
      <h1 style="color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px;">${metadata?.title || '简历'}</h1>
      <div style="margin: 20px 0;">
        <h2>个人信息</h2>
        <p><strong>姓名:</strong> ${resumeContent?.personal?.name || '未填写'}</p>
        <p><strong>职位:</strong> ${resumeContent?.personal?.title || '未填写'}</p>
        <p><strong>邮箱:</strong> ${resumeContent?.personal?.email || '未填写'}</p>
        <p><strong>电话:</strong> ${resumeContent?.personal?.phone || '未填写'}</p>
      </div>
      
      <div style="margin: 20px 0;">
        <h2>个人简介</h2>
        <p>${resumeContent?.summary || '暂无个人简介'}</p>
      </div>
      
      <div style="margin: 20px 0;">
        <h2>工作经历</h2>
        ${resumeContent?.experience?.map((exp: any) => `
          <div style="margin: 15px 0; padding: 15px; background: #f8f9fa; border-radius: 5px;">
            <h3>${exp.company || '未填写'} - ${exp.role || '未填写'}</h3>
            <p style="color: #666; font-size: 14px;">${exp.from || '未填写'} - ${exp.to || '至今'}</p>
            <ul>
              ${exp.highlights?.map((highlight: string) => `<li>${highlight}</li>`).join('') || '<li>暂无工作亮点</li>'}
            </ul>
          </div>
        `).join('') || '<p>暂无工作经历</p>'}
      </div>
      
      <div style="margin: 20px 0;">
        <h2>技能</h2>
        <ul>
          ${resumeContent?.skills?.map((skill: string) => `<li>${skill}</li>`).join('') || '<li>暂无技能信息</li>'}
        </ul>
      </div>
      
      <div style="margin: 20px 0;">
        <h2>教育背景</h2>
        ${resumeContent?.education?.map((edu: any) => `
          <div style="margin: 10px 0;">
            <h3>${edu.school || '未填写'} - ${edu.degree || '未填写'}</h3>
            <p style="color: #666;">${edu.year || '未填写'}</p>
          </div>
        `).join('') || '<p>暂无教育背景</p>'}
      </div>
      
      <div style="margin: 20px 0;">
        <h2>项目经验</h2>
        ${resumeContent?.projects?.map((project: any) => `
          <div style="margin: 15px 0; padding: 15px; background: #e9ecef; border-radius: 5px;">
            <h3>${project.name || '未填写'}</h3>
            <p>${project.description || '暂无描述'}</p>
            <ul>
              ${project.highlights?.map((highlight: string) => `<li>${highlight}</li>`).join('') || '<li>暂无项目亮点</li>'}
            </ul>
          </div>
        `).join('') || '<p>暂无项目经验</p>'}
      </div>
      
      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #dee2e6; text-align: center; color: #6c757d; font-size: 12px;">
        <p>Generated by ResumeAI - Professional Resume Analysis System</p>
        <p>Generated on: ${new Date().toLocaleDateString()}</p>
      </div>
    </div>
  `
  
  return await generateSimplePDFBlob(tempDiv)
}